#Complete Generated by ChatGPT to help flip sprite sheet images
import os
from PIL import Image

def flip_images_in_folder(input_folder, output_folder, flip_type="horizontal"):
    """
    Flips all images in the input folder and saves the flipped images to the output folder.

    Parameters:
        input_folder (str): Path to the folder containing input images.
        output_folder (str): Path to the folder where flipped images will be saved.
        flip_type (str): Type of flip, either 'horizontal' or 'vertical'.
    """
    try:
        # Ensure the output folder exists
        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        # List all files in the input folder
        for filename in os.listdir(input_folder):
            input_path = os.path.join(input_folder, filename)

            # Check if the file is an image
            if os.path.isfile(input_path) and filename.lower().endswith(('png', 'jpg', 'jpeg', 'bmp', 'gif')):
                try:
                    # Open the image
                    img = Image.open(input_path)

                    # Flip the image
                    if flip_type == "horizontal":
                        flipped_img = img.transpose(Image.FLIP_LEFT_RIGHT)
                    elif flip_type == "vertical":
                        flipped_img = img.transpose(Image.FLIP_TOP_BOTTOM)
                    else:
                        raise ValueError("Invalid flip_type. Use 'horizontal' or 'vertical'.")

                    # Save the flipped image
                    output_path = os.path.join(output_folder, filename)
                    flipped_img.save(output_path)
                    print(f"Flipped and saved: {filename}")

                except Exception as e:
                    print(f"Error processing {filename}: {e}")
            else:
                print(f"Skipping non-image file: {filename}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage
input_folder = "/Users/junninghu/Documents/15112_TP/15112_TP_Smash112/Graphics/Donatello_cropped/donatello_rAttack"
output_folder = "/Users/junninghu/Documents/15112_TP/15112_TP_Smash112/Graphics/Donatello_cropped/donatello_lAttack"
flip_type = "horizontal"  # Change to "vertical" for vertical flip

flip_images_in_folder(input_folder, output_folder, flip_type)

