#Begin Page Photo is generated by Dalle
#Shuriken Photo is from:
#https://www.spriters-resource.com/game_boy_advance/teenagemutantninjaturtlesubisoft/

from cmu_graphics import *
import Game_Char
import Game_Field
import BT

def onAppStart(app):
    app.width = 600
    app.height = 600
    app.gameOver = False
    app.rShuriLoc = '../Graphics/Shuriken/rShuriken'
    app.lShuriLoc = '../Graphics/Shuriken/lShuriken'
    app.rShuriSprite = [f'{app.rShuriLoc}/{i}-Photoroom.png' for i in range(3)]
    app.lShuriSprite = [f'{app.lShuriLoc}/{i}-Photoroom.png' for i in range(3)]
    reStart(app)
    

def reStart(app):
    app.aiMode = None
    app.counter = 0
    fieldSetUp(app)
    # Bullet
    app.projection = []
    #Player1 Basic Info and Sprite
    app.player1 = Game_Char.Donatello(app.width/4, app.height/4,'right', app.projection)
    app.player1StandInd = 0
    app.player1WalkInd = 0
    app.player1AttackInd = 0
    #Player2 Basic Info and Sprite
    app.player2 = Game_Char.Leonardo(3 * app.width/4, app.height/4,'left', app.projection)
    app.player2StandInd = 0
    app.player2WalkInd = 0
    app.player2AttackInd = 0
    #Bullet Fly
    app.bulletRightInd = 0
    app.bulletLeftInd = 0

def fieldSetUp(app):
    # Field
    app.field = Game_Field.Field()
    # Blocks
    app.ground = Game_Field.Block('ground', 0, 450, app.width, app.height)
    app.level1 = Game_Field.Block('level1', 400, 300, 30, 20)
    app.level2 = Game_Field.Block('level2', 200, 300, 30, 20)
    app.verticalBlock = Game_Field.Block('verticalBlock', app.width/2, 300, 20, 150)
    app.field.add(app.ground)
    app.field.add(app.level1)
    app.field.add(app.level2)
    app.field.add(app.verticalBlock)

# Start Screen

def start_redrawAll(app):
    drawImage('../Graphics/Background/beginBg.webp',
              0, 0, width = app.width, height = app.height)
    drawLabel('Welcome to Smash-112', app.width/2, app.height/5, size=40, 
              bold=True, fill = 'lightgreen')
    drawLabel('Press a to enter AI player mode', app.width/2, app.height/5*2, 
              size=24, fill = 'lightgreen')
    drawLabel('Press m to enter Multi-player mode', app.width/2, app.height/5*3, 
              size=24, fill = 'lightgreen')

def start_onKeyPress(app, key):
    if key == 'a' or key == 'm':
        if key == 'a':
            app.aiMode = True
        elif key == 'm':
            app.aiMode = False
        setActiveScreen('game')

# Game Screen

def game_redrawAll(app):
    # Draw Background
    drawImage('../Graphics/Background/10615.png', 0, 0, width = app.width, height = app.height)
    drawField(app)
    drawInstruction(app)
    drawPlayer1(app)
    drawPlayer2(app)
    drawBullet(app)
    

def drawField(app):
    for block in app.field.blocks:
        drawRect(block.x, block.y, block.sizeX, block.sizeY, fill = 'black')


def drawInstruction(app):
    drawLabel('Use w, a, s, d to move the Donatello', app.width/2, 20, size = 14)
    drawLabel('Use g to shoot the bullet from Donatello', app.width/2, 35, size = 14)
    drawLabel('Use up, left, down, right to move Leonardo', app.width/2, 50, size = 14)
    drawLabel('Use k to shoot the bullet from Leonardo', app.width/2, 65, size = 14)
    drawLabel('Red Circles indicate how many lives left', app.width/2, 80, size = 14)
    drawLabel('If game over, press r to restart', app.width/2, 95, size = 14)
    # Gameover:
    if app.gameOver == True:
        if app.aiMode == True:
            if app.player2.health == 0:
                drawLabel('You Win!', app.width/2, app.height/2, fill = 'red', size = 40)
            else:
                drawLabel('You Lose', app.width/2, app.height/2, fill = 'red', size = 40)
        else:
            if app.player1.health == 0:
                drawLabel('Player1 Win!', app.width/2, app.height/2, fill = 'red', size = 40)
            else:
                drawLabel('Player2 Win!', app.width/2, app.height/2, fill = 'red', size = 40)

def drawPlayer1(app):
    #Draw Player 1 lives left
    headDim = getImageSize(app.player1.headLoc)
    # Background
    drawRect(0, app.height - headDim[1]*1.5, 200, headDim[1]*1.5, fill = 'purple')
    drawLabel(f'{app.player1.name}', 70, app.height - 60, fill = 'purple', size = 20)
    drawRect(headDim[0]*1.5, app.height - headDim[1]*1.5 + 5,
             app.player1.health/5*150+0.1, headDim[1]*1.5 - 10, fill = 'red',
             border = 'silver', borderWidth = 2)
    #Head Profile
    drawImage(app.player1.headLoc, 0, app.height - headDim[1]*1.5, 
              width = headDim[0]*1.5, height = headDim[1]*1.5)
    # draw Player1 with Sprite
    if app.player1.direction == 'left': #Direction Left
        if app.player1.defend == True:
            drawCircle(app.player1.x, app.player1.y, 30, fill = 'red', opacity = 20, border = 'silver')
            drawImage(app.player1.lDefLoc, app.player1.x, app.player1.y, align = 'center')
        elif app.player1.attack:
            imageDimension = getImageSize(app.player1.lAttackSprite[app.player1AttackInd])
            imageWidth = imageDimension[0]
            drawImage(app.player1.lAttackSprite[app.player1AttackInd],
                      app.player1.x, app.player1.y,
                      width = imageWidth, height = app.player1.sizeY,
                      align = 'center')
        elif app.player1.walk: 
            drawImage(app.player1.lWalkSprite[app.player1WalkInd], app.player1.x, app.player1.y,
                    width = app.player1.sizeX, height = app.player1.sizeY,
                    align = 'center')
        else: 
            drawImage(app.player1.lStandSprite[app.player1StandInd], app.player1.x, app.player1.y,
                    width = app.player1.sizeX, height = app.player1.sizeY,
                    align = 'center')
    else: # Direction Right or Initial
        if app.player1.defend == True:
            drawCircle(app.player1.x, app.player1.y, 30, fill = 'red', opacity = 20, border = 'silver')
            drawImage(app.player1.rDefLoc, app.player1.x, app.player1.y, align = 'center')
        elif app.player1.attack:
            imageDimension = getImageSize(app.player1.rAttackSprite[app.player1AttackInd])
            imageWidth = imageDimension[0]
            drawImage(app.player1.rAttackSprite[app.player1AttackInd],
                      app.player1.x, app.player1.y,
                      width = imageWidth, height = app.player1.sizeY,
                      align = 'center')
        elif app.player1.walk:
            drawImage(app.player1.rWalkSprite[app.player1WalkInd], app.player1.x, app.player1.y,
                    width = app.player1.sizeX, height = app.player1.sizeY,
                    align = 'center')
        else:
            drawImage(app.player1.rStandSprite[app.player1StandInd], app.player1.x, app.player1.y,
                    width = app.player1.sizeX, height = app.player1.sizeY,
                    align = 'center')
    
    
    
def drawPlayer2(app):
    #Draw Player 2 lives left
    drawLabel('Leonardo health', app.width - 70, app.height - 40, fill = 'blue')
    for i in range(app.player2.health):
        drawCircle(app.width-30*(i+1), app.height - 20, 10, fill = 'red')
    headDim = getImageSize(app.player1.headLoc)
    # Background
    drawRect(app.width - 200, app.height - headDim[1]*1.5, 200, headDim[1]*1.5, 
             fill = 'blue')
    drawLabel(f'{app.player2.name}', app.width - 70, app.height - 60,
              fill = 'blue', size = 20)
    drawRect(app.width - headDim[0]*1.5 - (app.player2.health/5*150), 
             app.height - headDim[1]*1.5 + 5,
             app.player2.health/5*150+0.1, 
             headDim[1]*1.5 - 10, fill = 'red',
             border = 'silver', borderWidth = 2)
    #Head Profile
    drawImage(app.player2.headLoc, 
              app.width - headDim[0]*1.5, 
              app.height - headDim[1]*1.5, 
              width = headDim[0]*1.5, height = headDim[1]*1.5)

    # draw Player2 with Sprite
    if app.player2.direction == 'right':
        if app.player2.defend == True:
            drawCircle(app.player2.x, app.player2.y, 30, fill = 'red', opacity = 20, border = 'silver')
            drawImage(app.player2.rDefLoc, app.player2.x, app.player2.y, align = 'center')
        elif app.player2.attack:
            imageDimension = getImageSize(app.player2.rAttackSprite[app.player2AttackInd])
            imageWidth = imageDimension[0]
            drawImage(app.player2.rAttackSprite[app.player2AttackInd],
                      app.player2.x, app.player2.y,
                      width = imageWidth, height = app.player2.sizeY,
                      align = 'center')
        elif app.player2.walk: #Walk
            drawImage(app.player2.rWalkSprite[app.player2WalkInd], app.player2.x, app.player2.y,
                    width = app.player2.sizeX, height = app.player2.sizeY,
                    align = 'center')
        else: #Walk
            drawImage(app.player2.rStandSprite[app.player2StandInd], app.player2.x, app.player2.y,
                    width = app.player2.sizeX, height = app.player2.sizeY,
                    align = 'center')
    else:
        if app.player2.defend == True:
            drawCircle(app.player2.x, app.player2.y, 30, fill = 'red', opacity = 20, border = 'silver')
            drawImage(app.player2.lDefLoc, app.player2.x, app.player2.y, align = 'center')
        elif app.player2.attack:
            imageDimension = getImageSize(app.player2.lAttackSprite[app.player2AttackInd])
            imageWidth = imageDimension[0]
            drawImage(app.player2.lAttackSprite[app.player2AttackInd],
                      app.player2.x, app.player2.y,
                      width = imageWidth, height = app.player2.sizeY,
                      align = 'center')
        elif app.player2.walk:
            drawImage(app.player2.lWalkSprite[app.player2WalkInd], app.player2.x, app.player2.y,
                    width = app.player2.sizeX, height = app.player2.sizeY,
                    align = 'center')
        else:
            drawImage(app.player2.lStandSprite[app.player2StandInd], app.player2.x, app.player2.y,
                    width = app.player2.sizeX, height = app.player2.sizeY,
                    align = 'center')


def drawBullet(app):
    for bullet in app.projection:
        if bullet.velocity > 0:
            drawImage(app.rShuriSprite[app.bulletRightInd], bullet.x, 
                      bullet.y, width = bullet.sizeX, height = bullet.sizeY,
                      align = 'center')
        else:
            drawImage(app.lShuriSprite[app.bulletLeftInd], bullet.x, 
                      bullet.y, width = bullet.sizeX, height = bullet.sizeY,
                      align = 'center')

def game_onKeyPress(app, key):
    if not app.gameOver:
        #Jump
        if not app.player1.defend:
        # Player1 Action
            if key == 'w':
                if app.player1.jump == False:
                    app.player1.jumpChr()
            #Shoot the bullet
            if key == 'e' and app.player1.shuriCD == 0:
                app.player1.shootChr()
            if key == 'g' and app.player1.attackCD == 0:
                app.player1.attackChr()
                if (isHit(app.player1, app.player2) and app.player1.attack
                    and not app.player2.defend):
                    app.player2.health -= 1
        # Player2 Action
        if not app.player2.defend:
            if key == 'up':
                if app.player2.jump == False:
                    app.player2.jumpChr()
            if key == 'enter' and app.player2.shuriCD == 0:
                app.player2.shootChr()
            if key == 'k' and app.player2.attackCD == 0:
                app.player2.attackChr()
                if (isHit(app.player1, app.player2) and app.player2.attack
                    and not app.player1.defend):
                    app.player1.health -= 1
    #Restart the game
    if app.gameOver == True:
        if key == 'r':
            setActiveScreen('start')
            reStart(app)
            app.gameOver = False

def isHit(player1, player2):
    if (distance(player1.x+player1.sizeX/2, player1.y+player1.sizeY/2,
                player2.x+player2.sizeX/2, player2.y+player2.sizeY/2)
                < 50):
        return True
    else:
        return False
    

def game_onKeyHold(app, keys):
    if app.gameOver:
        return
    # Still Player1 Movement
    if 'h' in keys:
        app.player1.defend = True
    elif 'a' in keys:
        app.player1.direction = 'left'
        app.player1.walk = True #Determine Motion
        if not hitBlockRight(app, app.player1):
            app.player1.x -= 5
    elif 'd' in keys:
        app.player1.direction = 'right'
        app.player1.walk = True
        if not hitBlockLeft(app, app.player1):
            app.player1.x += 5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    if app.player1.x + app.player1.sizeX > app.width: #Bounded Motion
        app.player1.x = app.width-app.player1.sizeX
    elif app.player1.x < app.player1.sizeX/2:
        app.player1.x = app.player1.sizeX/2
    # Player2 Movement:
    if 'l' in keys:
        app.player2.defend = True
    elif 'left' in keys:
        app.player2.direction = 'left'
        app.player2.walk = True
        if not hitBlockRight(app, app.player2):
            app.player2.x -= 5
    elif 'right' in keys:
        app.player2.direction = 'right'
        app.player2.walk = True
        if not hitBlockLeft(app, app.player2):
            app.player2.x += 5
    if app.player2.x + app.player2.sizeX > app.width: #Bounded Motion
        app.player2.x = app.width-app.player2.sizeX
    elif app.player2.x < 0:
        app.player2.x = 0

def hitBlockRight(app, player):
    for block in app.field.blocks:
        if (block.y - player.sizeY/2 <= player.y 
            <= block.y+block.sizeY+player.sizeY/2):
            if (block.x + block.sizeX - 5 <= player.x - player.sizeX/2 
                <= block.x + block.sizeX):
                player.x = block.x + block.sizeX + player.sizeX/2
                return True
    return False

def hitBlockLeft(app, player):
    for block in app.field.blocks:
        if (block.y - player.sizeY/2 <= player.y 
            <= block.y+block.sizeY+player.sizeY/2):
            if (block.x <= player.x + player.sizeX/2 
                <= block.x + 5):
                player.x = block.x - player.sizeX/2
                return True
    return False



def game_onKeyRelease(app, key):
    if app.gameOver:
        return 
    if key == 'd':
        app.player1.walk = False
    elif key == 'a':
        app.player1.walk = False
    elif key == 'h':
        app.player1.defend = False
    if key == 'left':
        app.player2.walk = False
    elif key == 'right':
        app.player2.walk = False
    elif key == 'l':
        app.player2.defend = False


def game_onStep(app):
    if not app.gameOver:
        if app.aiMode == True:
            BT.btAiPlayer(app).tick()
        deterGameOver(app)
        gravSimul(app)
        bulletFly(app)
        bulletHit(app)
        spriteInd(app)
        shuriKenCD(app)
        attackCD(app)
        deterRise(app)
        playerLoc(app)
        bulletHitBlock(app)
        app.counter += 1

def playerLoc(app):
    for block in app.field.blocks:
        if onBlock(app.player1, block):
            app.player1.loc = f'{block}'
            break
        else:
            app.player1.loc = None

    for block in app.field.blocks:
        if onBlock(app.player2, block):
            app.player2.loc = f'{block}'
            break
        else:
            app.player2.loc = None

def deterRise(app):
    if app.player1.dy > 0:
        app.player1.rise = False
    else:
        app.player1.rise = True
    if app.player2.dy > 0:
        app.player2.rise = False
    else:
        app.player2.rise = True


def deterGameOver(app):
    if app.player1.health == 0 or app.player2.health == 0:
        app.gameOver = True


def attackCD(app):
    if app.player1.attackCD > 0:
        app.player1.attackCD -= 1
    if app.player2.attackCD > 0:
        app.player2.attackCD -= 1
        
def shuriKenCD(app):
    if app.player1.shuriCD > 0:
        app.player1.shuriCD -= 1
    if app.player2.shuriCD > 0:
        app.player2.shuriCD -= 1
            
def spriteInd(app):
    if app.counter % 2 == 0:
            #Player1 Sprite
            app.player1StandInd = (app.player1StandInd + 1) % len(app.player1.rStandSprite)
            app.player1WalkInd = (app.player1WalkInd + 1) % len(app.player1.rWalkSprite)
            if app.player1.attack:
                if app.player1AttackInd == len(app.player1.rAttackSprite)-1:
                    app.player1.attack = False
                    app.player1.attackCD = 15
                    app.player1.attackComb = 1
                    app.player1AttackInd = 0
                app.player1AttackInd += 1

            #Player2 Sprite
            app.player2StandInd = (app.player2StandInd + 1) % len(app.player2.rStandSprite)
            app.player2WalkInd = (app.player2WalkInd + 1) % len(app.player2.rWalkSprite)
            if app.player2.attack:
                if app.player2AttackInd == len(app.player2.rAttackSprite)-1:
                    app.player2.attack = False
                    app.player2.attackCD = 15
                    app.player2AttackInd = 0
                app.player2AttackInd += 1

            #Shuriken Sprite
            app.bulletRightInd = (app.bulletRightInd + 1) % len(app.rShuriSprite)
            app.bulletLeftInd = (app.bulletLeftInd + 1) % len(app.lShuriSprite)


#Gravity Simulation
def gravSimul(app):

    if app.player1.jump == True:
        app.player1.dy += 3
        app.player1.y += app.player1.dy

    
    for block in app.field.blocks:
        if onBlock(app.player1, block):
            app.player1.y = block.y - app.player1.sizeY/2
            app.player1.jump = False
            app.player1.dy = 0
            break
        else:
            app.player1.jump = True

        if downBlock(app.player1, block):
            app.player1.y = block.y + block.sizeY + app.player1.sizeY/2
            app.player1.dy = 0
            break

    
    # Player 2 Sim
    if app.player2.jump == True:
        app.player2.dy += 3
        app.player2.y += app.player2.dy
    
    for block in app.field.blocks:
        if onBlock(app.player2, block):
            app.player2.y = block.y - app.player2.sizeY/2
            app.player2.jump = False
            app.player2.dy = 0
            break
        else:
            app.player2.jump = True
        if downBlock(app.player2, block):
            app.player2.y = block.y + block.sizeY + app.player2.sizeY/2
            app.player2.dy = 0
            break




def onBlock(player, block):
    if block.x - player.sizeX/2 < player.x < block.x + block.sizeX + player.sizeX/2:
        if (block.y + player.dy - player.sizeY/2 >= player.y 
            >= block.y - player.sizeY/2): #The player.dy is used to correct error off by 2-3 pixels
            return True
    return False

def downBlock(player, block):
    if block.x - player.sizeX/2 <= player.x <= block.x + block.sizeX + player.sizeX/2:
        if block.y+block.sizeY+player.dy <= player.y-player.sizeY/2 <= block.y+block.sizeY:
            return True
    return False

#Bullet fly function
def bulletFly(app):
    index = 0
    while index < len(app.projection):
        app.projection[index].x += app.projection[index].velocity
        if app.projection[index].x - app.projection[index].sizeX < 0:
            app.projection.pop(index)
        elif app.projection[index].x + app.projection[index].sizeX > app.width:
            app.projection.pop(index)
        index += 1

# Bullet hit function
def bulletHit(app):
    i = 0
    while i < len(app.projection):
        if (distance(app.projection[i].x, app.projection[i].y, 
                     app.player1.x, app.player1.y)
            < app.projection[i].sizeX/2 + app.player1.sizeX/2):
            if not app.player1.defend:
                app.player1.health -= 1
            app.projection.pop(i)

        elif (distance(app.projection[i].x, app.projection[i].y, 
                       app.player2.x, app.player2.y)
            < app.projection[i].sizeX/2 + app.player2.sizeX/2):
            if not app.player2.defend:
                app.player2.health -= 1
            app.projection.pop(i)
        i += 1

#Bullet Disappear after hitting block
def bulletHitBlock(app):
    for block in app.field.blocks:
        i = 0
        while i < len(app.projection):
            #Ideas from CS Academy 1.4.11
            bottom1 = app.projection[i].y + app.projection[i].sizeY/2
            right1 = app.projection[i].x + app.projection[i].sizeX/2
            bottom2 = block.y + block.sizeY
            right2 = block.x + block.sizeX
            if (bottom1 >= block.y 
                and bottom2 >= app.projection[i].y - app.projection[i].sizeY/2 
                and right1 >= block.x
                and right2 >= app.projection[i].x - app.projection[i].sizeX/2):
                app.projection.pop(i)
            i += 1
                

#Helper Function
def distance(x1, y1, x2, y2):
    return ((x1-x2)**2+(y1-y2)**2)**0.5


runAppWithScreens(initialScreen = 'start')