#Begin Page, AI mode selection, Field Selection Photo, Character Selection Photo are generated by Dalle
#Shuriken Photo is from:
#https://www.spriters-resource.com/game_boy_advance/teenagemutantninjaturtlesubisoft/
#Setting Photo is from:
#https://www.iconpacks.net/free-icon/settings-3110.html
#Part of CS Academy Code is used for field selection

from cmu_graphics import *
import Game_Char
import Game_Field
import BT

def onAppStart(app):
    app.width = 800
    app.height = 600
    app.gameOver = False
    app.rShuriLoc = '../Graphics/Shuriken/rShuriken'
    app.lShuriLoc = '../Graphics/Shuriken/lShuriken'
    app.rShuriSprite = [f'{app.rShuriLoc}/{i}-Photoroom.png' for i in range(3)]
    app.lShuriSprite = [f'{app.lShuriLoc}/{i}-Photoroom.png' for i in range(3)]
    reStart(app)
    

def reStart(app):
    # Bullet
    app.projection = []
    #AiSelection Page
    app.aiMode = None
    app.selectCounter = 0
    app.counter = 0
    #FieldSelection Page
    Game_Field.fieldSetUp(app)
    Game_Field.fieldList(app)
    app.fieldSelection = (0, 0)
    app.selectedField = None
    #Character Selection
    Game_Char.characterList(app)
    app.player1Selection = 0
    app.player2Selection = 1
    app.player1ChoseStatus = False
    app.player2ChoseStatus = False
    # Game Pause
    app.pause = False
    #Player1 Basic Info and Sprite
    app.player1 = None
    app.player1StandInd = 0
    app.player1WalkInd = 0
    app.player1AttackInd = 0
    app.player1AntiDefInd = 0
    #Player2 Basic Info and Sprite
    app.player2 = None
    app.player2StandInd = 0
    app.player2WalkInd = 0
    app.player2AttackInd = 0
    app.player2AntiDefInd = 0
    #Bullet Fly
    app.bulletRightInd = 0
    app.bulletLeftInd = 0
    #Jump points:
    app.closetJumpPoint = None



# Start Screen

def start_redrawAll(app):
    drawImage('../Graphics/Background/beginBg.webp',
              0, 0, width = app.width, height = app.height)
    drawLabel('Welcome to Smash-112', app.width/2, app.height/15*6, size=46, 
              bold=True, fill = 'lightgreen')
    drawRect(0, app.height/3*2-12, app.width, 26, fill = 'black')
    drawLabel('Press any button to begin', app.width/2, app.height/3*2, 
              size=24, fill = 'lightgreen')

def start_onKeyPress(app, key):
    setActiveScreen('AiSelection')

#AI Selection Page
def AiSelection_redrawAll(app):
    drawImage('../Graphics/Background/ai_selection.webp',
              0, 0, width = app.width, height = app.height)
    if app.selectCounter % 2 == 0:
        drawRect(app.width/4, app.height/2, app.width/3, app.height/4, 
                 align = 'center', border = 'red', borderWidth = 2)
        drawRect(app.width/4*3, app.height/2, app.width/3, app.height/4, 
                 align = 'center')
    else:
        drawRect(app.width/4, app.height/2, app.width/3, app.height/4, 
                 align = 'center')
        drawRect(app.width/4*3, app.height/2, app.width/3, app.height/4, 
                 align = 'center', border = 'red', borderWidth = 2)
    drawLabel('Multi-player', app.width/4, app.height/2, fill = 'blue', size=36)
    drawLabel('AI Mode', app.width/4*3, app.height/2, fill = 'red', size=36)
    drawLabel('Use a and d, left and right to select', app.width/2, 100, 
              fill = 'gold', size = 36)
    drawLabel('Press enter to confirm selection', app.width/2, 
              150, fill = 'gold', size = 36)

def AiSelection_onKeyPress(app, key):
    if key == 'right' or key == 'd':
        app.selectCounter += 1
    elif key == 'left' or key == 'a':
        app.selectCounter -= 1
    elif key == 'enter':
        if app.selectCounter % 2 == 1:
            app.aiMode = True
        setActiveScreen('fieldSelection')

# Field Selection Page
def fieldSelection_redrawAll(app):
    drawImage('../Graphics/Background/fieldSelection.webp',
              0, 0, width = app.width, height = app.height)
    drawRect(app.width/4, app.height/2, app.width/3, app.height/3, 
             align = 'center', fill = None, border = 'black')
    drawRect(app.width/4, app.height/2 + app.height/5, app.width/3, 40,
             fill = 'purple', border = 'grey', align = 'center')
    currRow, currCol = app.fieldSelection[0], app.fieldSelection[1]
    name = app.fields[currRow][currCol].name
    drawLabel(f'{name}', app.width/4, app.height/2 + app.height/5, size = 22)
    drawLargView(app)
    drawRect(app.width/15*7, app.height/4 - 40, 150, 40, fill = 'purple')
    drawLabel('Field Selection', app.width/15*7 + 75, app.height/4 - 20, 
              size = 22)
    drawBoard(app)
    drawBoardBorder(app)
    drawLabel('Use "wasd" and up, left, down, right to select', app.width/2, 25, 
              fill = 'gold', size = 36)
    drawLabel('Press enter to confirm selection', app.width/2, 
              75, fill = 'gold', size = 36)

def drawLargView(app):
    currRow, currCol = app.fieldSelection[0], app.fieldSelection[1]
    relativeX = app.width/4 - app.width/6
    relativeY = app.height/2 - app.height/6
    if app.fields[currRow][currCol] != None:
        drawImage(app.fields[currRow][currCol].image, relativeX, relativeY, 
                width = app.width/3, height = app.height/3)
        for block in app.fields[currRow][currCol].blocks:
            minX = block.x/3
            minY = block.y/3
            minSizeX = block.sizeX/3
            minSizeY = block.sizeY/3
            drawRect(relativeX + minX, relativeY + minY, minSizeX, minSizeY, 
                     fill = block.color)

#Code below are from CS Academy##############

def fieldSelection_onKeyPress(app, key):
    if key == 'left' or key == 'a':    moveSelection(app, 0, -1)
    elif key == 'right' or key == 'd': moveSelection(app, 0, +1)
    elif key == 'up' or key == 'w':    moveSelection(app ,-1, 0)
    elif key == 'down' or key == 's':  moveSelection(app, +1, 0)
    if key == 'enter':
        currRow, currCol = app.fieldSelection[0], app.fieldSelection[1]
        app.selectedField = app.fields[currRow][currCol]
        setActiveScreen('characterSelection')

def moveSelection(app, drow, dcol):
    if app.fieldSelection != None:
        selectedRow, selectedCol = app.fieldSelection
        newSelectedRow = (selectedRow + drow) % 2
        newSelectedCol = (selectedCol + dcol) % 2
        app.fieldSelection = (newSelectedRow, newSelectedCol)

def drawBoard(app):
    for row in range(2):
        for col in range(2):
            drawCell(app, row, col)

def drawCell(app, row, col):
    cellLeft, cellTop = getCellLeftTop(app, row, col)
    cellWidth, cellHeight = getCellSize(app)
    color = 'red' if (row, col) == app.fieldSelection else 'black'
    borderWidth = 3 if (row, col) == app.fieldSelection else 1
    #Some of own code here to draw the mini window view
    if app.fields[row][col] != None:
        drawImage(app.fields[row][col].image, cellLeft, cellTop, 
                width = app.width/4, height = app.height/4)
        for block in app.fields[row][col].blocks:
            minX = block.x/4
            minY = block.y/4
            minSizeX = block.sizeX/4
            minSizeY = block.sizeY/4
            drawRect(cellLeft + minX, cellTop + minY, minSizeX, minSizeY, 
                     fill = block.color)
    drawRect(cellLeft, cellTop, cellWidth, cellHeight,
             fill=None, border= color,
             borderWidth=borderWidth)
    
def getCellLeftTop(app, row, col):
    cellWidth, cellHeight = getCellSize(app)
    cellLeft = app.width/15*7 + col * cellWidth
    cellTop = app.height/4 + row * cellHeight
    return (cellLeft, cellTop)

def getCellSize(app):
    cellWidth = app.width/2 / 2
    cellHeight = app.height/2 / 2
    return (cellWidth, cellHeight)

def drawBoardBorder(app):
  # draw the board outline (with double-thickness):
  drawRect(app.width/15*7, app.height/4, app.width/2, app.height/2,
           fill=None, border='black',
           borderWidth=2*1)

#Code above are from CS Academy##############

# Character Selection

def characterSelection_redrawAll(app):
    drawImage('../Graphics/Background/characterSelection.webp', 0, 0, 
              width = app.width,
              height = app.height)
    # Draw the selected player block
    drawRect(app.width/8, app.height - 300, 250, 50, fill = 'blue')
    drawLabel('Player1', app.width/8 + 250/2, app.height - 275, size = 25)
    drawRect(app.width/8, app.height-250, 250, 250, fill = 'grey', 
             border = 'black')
    drawRect(app.width-app.width/8, app.height - 300, 250, 50, fill = 'red', 
             align = 'right-top')
    drawLabel('Player2', app.width-225, app.height - 275, size = 25)
    drawRect(app.width-app.width/8, app.height-250, 250, 250, 
             align = 'right-top', fill = 'grey', border = 'black')
    
    # Draw the selected block
    for i in range(len(app.chrList)):
        drawRect(i*(app.width/5)+app.width/5, app.height/10, app.width/5, 
                 app.height/3, fill = 'grey')
        drawImage(f'{app.chrList[i].profileLoc}', i*(app.width/5)+app.width/5, 
                  app.height/10, width = app.width/5, height = app.height/3)
        drawRect(i*(app.width/5)+app.width/5, app.height/10, app.width/5, 
                    app.height/3, fill = None, border = 'black', 
                    borderWidth = 10)
        color = None
        if app.player1Selection != app.player2Selection:
            if i == app.player1Selection:
                color = 'blue'
                drawImage(f'{app.chrList[i].profileLoc}', 125, app.height-250, 
                        width = 225, height = 200)
            elif i == app.player2Selection:
                color = 'red'
                drawImage(f'{app.chrList[i].profileLoc}', 675, 
                        app.height-250, width = 225, height = 200, 
                        align = 'right-top')
            drawRect(i*(app.width/5)+app.width/5, app.height/10, app.width/5, 
                    app.height/3, fill = None, border = color, borderWidth = 10)
    if app.player1ChoseStatus:
        drawLabel('Ready', 125 + 225/2, 575, fill = 'blue', size = 30)
    if app.player2ChoseStatus:
        drawLabel('Ready', 675 - 225/2, 575, fill = 'red', size = 30)
    if app.player1Selection == app.player2Selection:
        drawLabel('You cannot choose the same character!', app.width/2, 
                  app.height/2, fill = 'darkRed', size = 30)
    drawLabel('Use a and d, left and right to select', app.width/2, 20, 
              fill = 'gold', size = 24)
    drawLabel('Press enter to g for player 1, j for player 2 to confirm', 
              app.width/2, 45, fill = 'gold', size = 24)
        

def characterSelection_onKeyPress(app, key):
    if key == 'd':
        app.player1Selection += 1
        app.player1Selection %= 3
    elif key == 'a':
        app.player1Selection -= 1
        app.player1Selection %= 3
    if key == 'left':
        app.player2Selection -= 1
        app.player2Selection %= 3
    elif key == 'right':
        app.player2Selection += 1
        app.player2Selection %= 3
    if app.player1Selection != app.player2Selection:
        if key == 'g':
            if app.player1ChoseStatus:
                app.player1ChoseStatus = False
                app.player1.x = None
                app.player1.direction = None
                app.player1 = None
            else:
                app.player1ChoseStatus = True
                app.player1 = app.chrList[app.player1Selection]
                app.player1.x = app.width/4
                app.player1.direction = 'right'
        if key == 'j':
            if app.player2ChoseStatus:
                app.player2ChoseStatus = False
                app.player2.x = None
                app.player2.direction = None
                app.player2 = None
            else:
                app.player2ChoseStatus = True
                app.player2 = app.chrList[app.player2Selection]
                app.player2.x = app.width/4*3
                app.player2.direction = 'left'

def characterSelection_onStep(app):
    if app.player1ChoseStatus and app.player2ChoseStatus:
        setActiveScreen('gameInstruction')

#Game Instruction

def gameInstruction_redrawAll(app):
    drawImage('../Graphics/Background/gameInstruction.webp', 0, 0,
              width = app.width, height = app.height)
    drawRect(app.width/8, app.height/8, app.width/8*6, app.height/8*6, 
             fill = 'grey')
    drawLabel('Use w, a, s, d to move player 1', app.width/2, 100, size = 20)
    drawLabel('Use up, left, down, right to move player 2', app.width/2, 130, 
              size = 20)
    drawImage('../Graphics/instruction/walk.png', app.width/2, 180, 
              align = 'center')
    drawLabel('Use e to shoot, g to attack, h to defend and f to antidefend', 
              app.width/2, 230, size = 20)
    drawLabel('Use enter to shoot, l to attack, ":" to defend and k to antidefend', 
              app.width/2,260, size = 20)
    drawImage('../Graphics/instruction/attack.png', app.width/4, 330, 
              align = 'center')
    drawImage('../Graphics/instruction/defend.png', app.width/4*2, 330, 
              align = 'center')
    drawImage('../Graphics/instruction/antiDefend.png', app.width/4*3, 330, 
              align = 'center')
    drawLabel('Health Bar indicate how many lives left', app.width/2, 400, 
              size = 20)
    drawImage('../Graphics/instruction/healthBar.png', app.width/2, 450, 
              align = 'center')
    drawLabel('Press any button to enter fighting field', app.width/2, 500, 
              size = 30)

def gameInstruction_onKeyPress(app, key):
    setActiveScreen('game')

# Game Screen

def game_redrawAll(app):
    # Draw Background
    drawImage(app.selectedField.image, 0, 0, width = app.width, 
              height = app.height)
    drawField(app)
    drawInstruction(app)
    drawPlayer(app, app.player1, app.player1AntiDefInd, app.player1AttackInd,
               app.player1WalkInd, app.player1StandInd)
    drawPlayer(app, app.player2, app.player2AntiDefInd, app.player2AttackInd,
               app.player2WalkInd, app.player2StandInd)
    drawPlayerHealth(app)
    drawBullet(app)
    drawButton(app)

def drawButton(app):
    drawImage('../Graphics/Background/setting.png', app.width - 70, 20, 
              width = 50, height = 50)
    if app.pause:
        drawRect(app.width/3, app.height/4, app.width/3, app.height/2, 
                 fill = 'grey')
        drawLabel('Resume', app.width/2, app.height/4+80, size = 40)
        drawRect(app.width/2, app.height/4+80, 200, 50, fill = None, 
                 border = 'black', align = 'center')
        drawLabel('Restart', app.width/2, app.height/4+200, size = 40)
        drawRect(app.width/2, app.height/4+200, 200, 50, fill = None, 
                 border = 'black', align = 'center')
  
# Draw the fighting field
def drawField(app):
    for block in app.selectedField.blocks:
        drawRect(block.x, block.y, block.sizeX, block.sizeY, fill = block.color)


def drawInstruction(app):
    # Gameover:
    if app.gameOver == True:
        drawLabel('Press r to restart', app.width/2, app.height/2+50, 
                  fill = 'red', size = 40)
        if app.aiMode == True:
            if app.player2.health == 0.1:
                drawLabel('You Win!', app.width/2, app.height/2, fill = 'red', 
                          size = 40)
            else:
                drawLabel('You Lose', app.width/2, app.height/2, fill = 'red', 
                          size = 40)
        else:
            if app.player1.health == 0.1:
                drawLabel('Player2 Win!', app.width/2, app.height/2, 
                          fill = 'red', size = 40)
            else:
                drawLabel('Player1 Win!', app.width/2, app.height/2, 
                          fill = 'red', size = 40)

def drawPlayerHealth(app):
    #Draw Player 1 lives left
    headDim1 = getImageSize(app.player1.headLoc)
    # Background
    drawRect(0, app.height - headDim1[1]*1.5, 200, headDim1[1]*1.5, 
             fill = 'purple')
    drawLabel(f'{app.player1.name}', 70, app.height - 60, fill = 'purple', 
              size = 20)
    drawRect(headDim1[0]*1.5, app.height - headDim1[1]*1.5 + 5,
             app.player1.health/5*150+0.1, headDim1[1]*1.5 - 10, fill = 'red',
             border = 'silver', borderWidth = 2)
    #Head Profile
    drawImage(app.player1.headLoc, 0, app.height - headDim1[1]*1.5, 
              width = headDim1[0]*1.5, height = headDim1[1]*1.5)
    #Draw Player 2 lives left
    drawLabel(f'{app.player2.name}', app.width - 70, app.height - 40, 
              fill = 'blue')
    headDim2 = getImageSize(app.player1.headLoc)
    # Background
    drawRect(app.width - 200, app.height - headDim2[1]*1.5, 200, 
             headDim2[1]*1.5, fill = 'blue')
    drawLabel(f'{app.player2.name}', app.width - 70, app.height - 60,
              fill = 'blue', size = 20)
    drawRect(app.width - headDim2[0]*1.5 - (app.player2.health/5*150), 
             app.height - headDim2[1]*1.5 + 5,
             app.player2.health/5*150+0.1, 
             headDim2[1]*1.5 - 10, fill = 'red',
             border = 'silver', borderWidth = 2)
    #Head Profile
    drawImage(app.player2.headLoc, 
              app.width - headDim2[0]*1.5, 
              app.height - headDim2[1]*1.5, 
              width = headDim2[0]*1.5, height = headDim2[1]*1.5)

def drawPlayer(app, player, playerAntiDefInd, playerAttackInd, playerWalkInd, 
               playerStandInd):
    if player.direction == 'left': #Direction Left
        if player.antiDefendAni:
            imageDimension = getImageSize(player.antiLDefSprite[playerAntiDefInd])
            imageWidth = imageDimension[0]
            imageHeight = imageDimension[1]
            drawImage(player.antiLDefSprite[playerAntiDefInd],
                      player.x, player.y-imageHeight/4,
                      width = imageWidth, height = imageHeight,
                      align = 'center')
        elif player.defend:
            drawCircle(player.x, player.y, 30, fill = 'red', opacity = 20, 
                       border = 'silver')
            drawImage(player.lDefLoc, player.x, player.y, align = 'center')
        elif player.attackAni:
            imageDimension = getImageSize(player.lAttackSprite[playerAttackInd])
            imageWidth = imageDimension[0]
            drawImage(player.lAttackSprite[playerAttackInd],
                      player.x, player.y,
                      width = imageWidth, height = player.sizeY,
                      align = 'center')
        elif player.walk: 
            drawImage(player.lWalkSprite[playerWalkInd], player.x, player.y,
                    width = player.sizeX, height = player.sizeY,
                    align = 'center')
        else: 
            drawImage(player.lStandSprite[playerStandInd], player.x, player.y,
                    width = player.sizeX, height = player.sizeY,
                    align = 'center')
    elif player.direction == 'right': # Direction Right
        if player.antiDefendAni:
            imageDimension = getImageSize(player.antiRDefSprite[app.player1AntiDefInd])
            imageWidth = imageDimension[0]
            imageHeight = imageDimension[1]
            drawImage(player.antiRDefSprite[app.player1AntiDefInd],
                      player.x, player.y-imageHeight/4,
                      width = imageWidth, height = imageHeight,
                      align = 'center')
        elif player.defend:
            drawCircle(player.x, player.y, 30, fill = 'red', opacity = 20, 
                       border = 'silver')
            drawImage(player.rDefLoc, player.x, player.y, align = 'center')
        elif player.attackAni:
            imageDimension = getImageSize(player.rAttackSprite[app.player1AttackInd])
            imageWidth = imageDimension[0]
            drawImage(player.rAttackSprite[app.player1AttackInd],
                      player.x, player.y,
                      width = imageWidth, height = player.sizeY,
                      align = 'center')
        elif player.walk:
            drawImage(player.rWalkSprite[app.player1WalkInd], player.x, player.y,
                    width = player.sizeX, height = player.sizeY,
                    align = 'center')
        else:
            drawImage(player.rStandSprite[app.player1StandInd], player.x, player.y,
                    width = player.sizeX, height = player.sizeY,
                    align = 'center')


def drawBullet(app):
    for bullet in app.projection:
        if bullet.velocity > 0:
            drawImage(app.rShuriSprite[app.bulletRightInd], bullet.x, 
                      bullet.y, width = bullet.sizeX, height = bullet.sizeY,
                      align = 'center')
        else:
            drawImage(app.lShuriSprite[app.bulletLeftInd], bullet.x, 
                      bullet.y, width = bullet.sizeX, height = bullet.sizeY,
                      align = 'center')

def game_onKeyPress(app, key):
    if not app.gameOver:
        #Jump
        if not app.pause:
            if not app.player1.defend:
            # Player1 Action
                if key == 'w':
                    if app.player1.jump == False:
                        app.player1.jumpChr()
                #Shoot the bullet
                if key == 'e' and app.player1.shuriCD == 0:
                    app.player1.shootChr()
                elif key == 'g' and app.player1.attackCD == 0:
                    app.player1.attackChr()
                elif key == 'f' and app.player1.antiDefCD == 0:
                    app.player1.antiDefendChr()
                    
            # Player2 Action
            if not app.player2.defend:
                if key == 'up':
                    if app.player2.jump == False:
                        app.player2.jumpChr()
                if key == 'enter' and app.player2.shuriCD == 0:
                    app.player2.shootChr()
                elif key == 'k' and app.player2.attackCD == 0:
                    app.player2.attackChr()
                elif key == ';' and app.player2.antiDefCD == 0:
                    app.player2.antiDefendChr()

                
    #Restart the game
    if app.gameOver == True:
        if key == 'r':
            setActiveScreen('start')
            reStart(app)
            app.gameOver = False

# Determine whether is in the normal attack range
def isHit(player1, player2):
    if (distance(player1.x+player1.sizeX/2, player1.y+player1.sizeY/2,
                player2.x+player2.sizeX/2, player2.y+player2.sizeY/2)
                < 50):
        return True
    else:
        return False    

def game_onKeyHold(app, keys):
    if app.gameOver:
        return
    # Still Player1 Movement
    if not app.pause:
        if 'h' in keys:
            app.player1.defend = True
        elif 'a' in keys:
            app.player1.direction = 'left'
            app.player1.walk = True #Determine Motion
            app.player1.dx = -5
        elif 'd' in keys:
            app.player1.direction = 'right'
            app.player1.walk = True
            app.player1.dx = 5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        
        # Player2 Movement:
        if 'l' in keys:
            app.player2.defend = True
        elif 'left' in keys:
            app.player2.direction = 'left'
            app.player2.walk = True
            app.player2.dx = -5
        elif 'right' in keys:
            app.player2.direction = 'right'
            app.player2.walk = True
            app.player2.dx = 5
    

def game_onKeyRelease(app, key):
    if app.gameOver:
        return 
    if not app.pause:
        if key == 'd' or key == 'a':
            app.player1.walk = False
            app.player1.dx = 0
        elif key == 'h':
            app.player1.defend = False
        if key == 'left' or key == 'right':
            app.player2.walk = False
            app.player2.dx = 0
        elif key == 'l':
            app.player2.defend = False

def game_onMousePress(app, mouseX, mouseY):
    if not app.gameOver:
        if not app.pause:
            if (app.width - 70 < mouseX < app.width - 20
                and 20 < mouseY < 70):
                app.pause = True
        if app.pause:
            if (app.width/2 - 100 < mouseX < app.width/2 + 100
                and app.height/4+55 < mouseY < app.height/4+105):
                app.pause = False
            if (app.width/2 - 100 < mouseX < app.width/2 + 100
                and app.height/4+175 < mouseY < app.height/4+225):
                setActiveScreen('start')
                reStart(app)


def game_onStep(app):
    if not app.gameOver:
        if not app.pause:
            if app.aiMode == True:
                BT.btAiPlayer(app).tick()
            deterGameOver(app)
            gravSimul(app)
            bulletFly(app)
            bulletHit(app)
            spriteInd(app)
            attackCD(app)
            bulletHitBlock(app)
            walkMot(app)
            boundedMotion(app)
            deterAtt(app)
            bloodFixed(app)
            app.counter += 1

# Prevent bugs where health bar can go non-positive
def bloodFixed(app):
    if app.player1.health <= 0:
        app.player1.health = 0.1
    elif app.player2.health <= 0:
        app.player2.health = 0.1

# Determine whether attack deal damage
def deterAtt(app):
    if (isHit(app.player1, app.player2) and app.player2.attack
                    and not app.player1.defend):
                    app.player1.health -= 1
                    app.player2.attack = False
    elif (isHit(app.player1, app.player2) and app.player1.attack
                    and not app.player2.defend):
                    app.player2.health -= 1
                    app.player1.attack = False
    elif (isHit(app.player1, app.player2) and app.player2.antiDefend
                    and app.player1.defend):
                    app.player1.health -= 1
                    app.player1.defend = False
                    app.player2.antiDefend = False
    elif (isHit(app.player1, app.player2) and app.player1.antiDefend
                    and app.player2.defend):
                    app.player2.health -= 1
                    app.player2.defend = False
                    app.player1.antiDefend = False


def deterGameOver(app):
    if app.player1.health == 0.1 or app.player2.health == 0.1:
        app.gameOver = True

# Count all the abilities' CD
def attackCD(app):
    #Normal Attack
    if app.player1.attackCD > 0:
        app.player1.attackCD -= 1
    if app.player2.attackCD > 0:
        app.player2.attackCD -= 1
    #Bullet
    if app.player1.shuriCD > 0:
        app.player1.shuriCD -= 1
    if app.player2.shuriCD > 0:
        app.player2.shuriCD -= 1
    #AntiDefend
    if app.player1.antiDefCD > 0:
        app.player1.antiDefCD -= 1
    if app.player2.antiDefCD > 0:
        app.player2.antiDefCD -= 1
    

# Increment the sprite image index
def spriteInd(app):
    if app.counter % 2 == 0:
        #Player1 Sprite
        app.player1StandInd = ((app.player1StandInd + 1) 
                               % len(app.player1.rStandSprite))
        app.player1WalkInd = ((app.player1WalkInd + 1) 
                              % len(app.player1.rWalkSprite))
        if app.player1.attackAni:
            if app.player1AttackInd == len(app.player1.rAttackSprite)-1:
                app.player1.attack = False
                app.player1.attackAni = False
                app.player1.attackComb = 1
                app.player1AttackInd = 0
            app.player1AttackInd += 1

        #Player2 Sprite
        app.player2StandInd = ((app.player2StandInd + 1) 
                               % len(app.player2.rStandSprite))
        app.player2WalkInd = ((app.player2WalkInd + 1) 
                              % len(app.player2.rWalkSprite))
        if app.player2.attackAni:
            if app.player2AttackInd == len(app.player2.rAttackSprite)-1:
                app.player2.attack = False
                app.player2.attackAni = False
                app.player2AttackInd = 0
            app.player2AttackInd += 1

        #Shuriken Sprite
        app.bulletRightInd = (app.bulletRightInd + 1) % len(app.rShuriSprite)
        app.bulletLeftInd = (app.bulletLeftInd + 1) % len(app.lShuriSprite)

    if app.counter % 4 == 0:
        # AntiDefense Sprite
        if app.player1.antiDefendAni:
            if app.player1AntiDefInd == len(app.player1.antiRDefSprite)-1:
                app.player1.antiDefend = False
                app.player1.antiDefendAni = False
                app.player1.antiDefCD = 30
                app.player1AntiDefInd = 0
            app.player1AntiDefInd += 1

        if app.player2.antiDefendAni:
            if app.player2AntiDefInd == len(app.player2.antiRDefSprite)-1:
                app.player2.antiDefend = False
                app.player2.antiDefendAni = False
                app.player2.antiDefCD = 30
                app.player2AntiDefInd = 0
            app.player2AntiDefInd += 1

# Determine whether character hits the block
def boundedMotion(app):
    hitBlockLeft(app, app.player1)
    hitBlockLeft(app, app.player2)
    hitBlockRight(app, app.player1)
    hitBlockRight(app, app.player2)
    hitFrame(app)

# Determine if the character hit the left or right most side
def hitFrame(app):
    if app.player1.x + app.player1.sizeX > app.width: #Bounded Motion
        app.player1.x = app.width-app.player1.sizeX
    elif app.player1.x < app.player1.sizeX/2:
        app.player1.x = app.player1.sizeX/2
    if app.player2.x + app.player2.sizeX > app.width: #Bounded Motion
        app.player2.x = app.width-app.player2.sizeX
    elif app.player2.x < 0:
        app.player2.x = 0
    
# Determine if the character hit the block on left or right side
def hitBlockRight(app, player):
    for block in app.selectedField.blocks:
        if (block.y - player.sizeY/2 <= player.y 
            <= block.y+block.sizeY+player.sizeY/2):
            if (block.x + block.sizeX - 5 <= player.x - player.sizeX/2 
                <= block.x + block.sizeX):
                player.x = block.x + block.sizeX + player.sizeX/2


def hitBlockLeft(app, player):
    for block in app.selectedField.blocks:
        if (block.y - player.sizeY/2 <= player.y 
            <= block.y+block.sizeY+player.sizeY/2):
            if (block.x <= player.x + player.sizeX/2 
                <= block.x + 5):
                player.x = block.x - player.sizeX/2



#Gravity Simulation
def gravSimul(app):

    if app.player1.jump == True:
        app.player1.dy += 3
        app.player1.y += app.player1.dy

    
    for block in app.selectedField.blocks:
        if onBlock(app.player1, block):
            app.player1.y = block.y - app.player1.sizeY/2
            app.player1.jump = False
            app.player1.dy = 0
            break
        else:
            app.player1.jump = True

        if downBlock(app.player1, block):
            app.player1.y = block.y + block.sizeY + app.player1.sizeY/2
            app.player1.dy = 0
            break

    
    # Player 2 Sim
    if app.player2.jump == True:
        app.player2.dy += 3
        app.player2.y += app.player2.dy
    
    for block in app.selectedField.blocks:
        if onBlock(app.player2, block):
            app.player2.y = block.y - app.player2.sizeY/2
            app.player2.jump = False
            app.player2.dy = 0
            break
        else:
            app.player2.jump = True
        if downBlock(app.player2, block):
            app.player2.y = block.y + block.sizeY + app.player2.sizeY/2
            app.player2.dy = 0
            break

# Perform Walk Motion
def walkMot(app):
    if not app.player1.defend:
        app.player1.x += app.player1.dx
    if not app.player2.defend:
        app.player2.x += app.player2.dx
    

# Whether the character stands on the block
def onBlock(player, block):
    if (block.x - player.sizeX/2 < player.x 
        < block.x + block.sizeX + player.sizeX/2):
        if (block.y + player.dy - player.sizeY/2 >= player.y 
            >= block.y - player.sizeY/2): #The player.dy is used to correct error off by 2-3 pixels
            return True
    return False

# Whether the character hits the bottom of the block
def downBlock(player, block):
    if (block.x - player.sizeX/2 <= player.x 
        <= block.x + block.sizeX + player.sizeX/2):
        if (block.y+block.sizeY+player.dy <= player.y-player.sizeY/2 
            <= block.y+block.sizeY):
            return True
    return False

#Bullet fly function
def bulletFly(app):
    index = 0
    while index < len(app.projection):
        app.projection[index].x += app.projection[index].velocity
        if app.projection[index].x - app.projection[index].sizeX < 0:
            app.projection.pop(index)
        elif app.projection[index].x + app.projection[index].sizeX > app.width:
            app.projection.pop(index)
        index += 1

# Bullet hit function
def bulletHit(app):
    i = 0
    while i < len(app.projection):
        if (distance(app.projection[i].x, app.projection[i].y, 
                     app.player1.x, app.player1.y)
            < app.projection[i].sizeX/2 + app.player1.sizeX/2):
            if not app.player1.defend:
                app.player1.health -= 1
            app.projection.pop(i)

        elif (distance(app.projection[i].x, app.projection[i].y, 
                       app.player2.x, app.player2.y)
            < app.projection[i].sizeX/2 + app.player2.sizeX/2):
            if not app.player2.defend:
                app.player2.health -= 1
            app.projection.pop(i)
        i += 1

#Bullet Disappear after hitting block
def bulletHitBlock(app):
    for block in app.selectedField.blocks:
        i = 0
        while i < len(app.projection):
            #Ideas from CS Academy 1.4.11
            bottom1 = app.projection[i].y + app.projection[i].sizeY/2
            right1 = app.projection[i].x + app.projection[i].sizeX/2
            bottom2 = block.y + block.sizeY
            right2 = block.x + block.sizeX
            if (bottom1 >= block.y 
                and bottom2 >= app.projection[i].y - app.projection[i].sizeY/2 
                and right1 >= block.x
                and right2 >= app.projection[i].x - app.projection[i].sizeX/2):
                app.projection.pop(i)
            i += 1
                

#Helper Function
def distance(x1, y1, x2, y2):
    return ((x1-x2)**2+(y1-y2)**2)**0.5


runAppWithScreens(initialScreen = 'start')